development:
  adapter: mysql2
  encoding: utf8
  database: bk_dev
  username: root
  password: "fallleaf"
  host: 127.0.0.1

test:
  adapter: mysql2
  encoding: utf8
  database: bk_test
  username: root
  password: "fallleaf"
  host: 127.0.0.1

